from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
import os
import io
import qrcode
from PIL import Image as PILImage

def _generate_qr_code(url: str) -> io.BytesIO:
    qr = qrcode.QRCode(version=1, box_size=10, border=0)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white").convert("RGB")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf

def generate_forensic_pdf(scan_result, lang="en"):
    # Ensure outputs directory exists
    current_dir = os.path.dirname(os.path.abspath(__file__))
    outputs_dir = os.path.abspath(os.path.join(current_dir, "..", "..", "outputs"))
    os.makedirs(outputs_dir, exist_ok=True)
    
    file_id = scan_result.get("file_id", "scan")
    pdf_filename = f"forensic_report_{file_id}.pdf"
    pdf_path = os.path.join(outputs_dir, pdf_filename)
    
    doc = SimpleDocTemplate(pdf_path, pagesize=A4)
    story = []
    
    styles = getSampleStyleSheet()
    H1 = styles['Heading1']
    H2 = styles['Heading2']
    Normal = styles['Normal']
    
    verdict = scan_result.get('verdict', 'UNVERIFIED')
    confidence = scan_result.get('confidence', 50.0)
    
    # Cover page with verdict
    story.append(Paragraph(f"<b>{verdict} ({confidence:.1f}%)</b>", style=H1))
    
    exec_summary = scan_result.get('executive_summary', {})
    summary_text = exec_summary.get(lang, exec_summary.get('en', 'No summary available.'))
    story.append(Paragraph(summary_text, style=Normal))
    story.append(Spacer(1, 20))
    
    # Technical breakdown
    story.append(Paragraph("Technical Analysis:", style=H2))
    ela_score = scan_result.get('verdict_breakdown', {}).get('ela_contribution', 0)
    story.append(Paragraph(f"ELA Tampering: {ela_score:.1f}%", style=Normal))
    
    # Try to load heatmap if available
    try:
        heatmap_url = scan_result.get('visualizations', {}).get('ela_heatmap', '')
        # In a real scenario we might decode base64 or load from disk. 
        # For hackathon mockup, we'll draw a dummy if missing or skip.
        heatmap_filename = f"{file_id}_heatmap.png"
        heatmap_path = os.path.join(outputs_dir, heatmap_filename)
        if os.path.exists(heatmap_path):
            story.append(RLImage(heatmap_path, width=400, height=300))
    except Exception as e:
        print(f"Image load error: {e}")
        
    story.append(Spacer(1, 40))
    
    # Generate QR Code
    verify_url = f"https://phantomproof.ai/verify/{file_id}"
    qr_buf = _generate_qr_code(verify_url)
    qr_image = RLImage(qr_buf, width=2.5*cm, height=2.5*cm)
    
    footer_text = Paragraph(
        f"<b>This report was generated by PHANTOMPROOF.ai</b><br/>"
        f"For verification, scan the QR code or visit phantomproof.ai/verify/{file_id}",
        Normal
    )
    
    footer_table = Table([[qr_image, footer_text]], colWidths=[3*cm, 13*cm])
    footer_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (0, 0), "RIGHT"),
        ("VALIGN", (0, 0), (0, 0), "MIDDLE"),
        ("ALIGN", (1, 0), (1, 0), "LEFT"),
        ("VALIGN", (1, 0), (1, 0), "MIDDLE"),
        ("LEFTPADDING", (1, 0), (1, 0), 10),
    ]))
    story.append(footer_table)
        
    doc.build(story)
    return f"/reports/{pdf_filename}"
